name: ExItems
version: ${project.version}
main: tokyo.ini.exitems.ExItems
api-version: 1.16
load: STARTUP
commands:
  exitem:
    aliases: [ ei ]
    description: Ex-Items's main command
    usage: Usage:/<command> <sub command>
