name: ExItems
version: ${project.version}
main: tokyo.ini.exitems.ExItems
api-version: 1.16
load: STARTUP
commands:
  exitem:
    aliases: [ ei ]
    description: You can get the "books with a command (a.k.a. Ex-Item)" through a command
    usage: Usage:/<command> <name> <want command> <option>
  giveexitem:
    aliases: [ gi ]
    description: You can give the Ex-Item to other player through a this command
    usage: Usage:/<command> <Player's name>
